# Generated by Django 2.1.7 on 2021-04-02 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210402_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 16, 0, 39, 774849)),
        ),
    ]
