# Generated by Django 3.1.7 on 2021-04-05 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210405_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 23, 6, 59, 725117)),
        ),
    ]
