# Generated by Django 2.1.7 on 2021-04-04 21:31

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210404_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://www.mcebiscoo.com/wp-content/uploads/2020/03/brothersrapelaptop.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 0, 31, 47, 16610)),
        ),
    ]
