# Generated by Django 2.1.7 on 2021-04-04 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210405_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 0, 53, 14, 844680)),
        ),
    ]
