# Generated by Django 3.1.7 on 2021-04-05 08:40

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210405_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 11, 40, 39, 805041)),
        ),
    ]
